---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    yum:
      name: '*'
      state: latest  

  - name: Install httpd package 
    package:
      name: httpd
      state: present

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Install php for PHP support
    yum:
      name: php
      state: present

  - name: Restart Apache to apply changes
    service:
      name: httpd
      state: restarted

