---

- hosts: all
  become: true
  tasks:

  - name: stop and disable httpd service
    service:
      name: httpd
      state: stopped
      enabled: no

  - name: Remove httpd and php packages 
    yum:
      name: 
         - httpd
         - php
      state: absent     


        
